# Liste des services utilisé
services:
    # Partie PHP
    php:
        build:
            context: .
            dockerfile: ./config/php/Dockerfile
        volumes:
            - ./src:/var/www/html
            - ./config/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "7070:80"
        networks:
            - webnet
    # Partie MariaDB
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: Template_DB_apache
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        volumes:
        - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
        - "7000:3306"
        networks:
            - webnet
# Configuration networks
networks:
    webnet:
        driver: bridge